language: php

php:
  - 5.5
  - 5.6
  - system
  - hhvm

sudo: false

env:
  global:
    - COMPOSER_ROOT_VERSION=dev-master
  matrix:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest"

before_install:
    - >
      if [[ "$TRAVIS_PHP_VERSION" == "system" ]]; then
        pushd $HOME;
        git clone https://github.com/php/php-src.git;
        pushd php-src;
        ./buildconf -f;
        ./configure --prefix=$HOME/.phpenv/versions/7 \
            --with-curl --enable-exif \
            && make && make install;
        phpenv global 7;
        popd; popd;
        php --version;
        mkdir $PWD/phar;
        wget http://getcomposer.org/composer.phar -O $PWD/phar/composer;
        wget https://phar.phpunit.de/phpunit.phar -O $PWD/phar/phpunit;
        chmod +x $PWD/phar/*;
        export PATH=$PWD/phar:$PATH;
      fi

install:
  - composer self-update
  - composer update $COMPOSER_OPTS

script:
  - phpunit tests
  - ./tests/lint.sh

git:
  depth: 5
