language: php

php:
  - 5.5
  - 5.6
  - hhvm

env:
  global:
    - COMPOSER_ROOT_VERSION=dev-master
  matrix:
    - COMPOSER_OPTS=""
    - COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update
  - composer update $COMPOSER_OPTS

script:
  - phpunit tests
  - ./tests/lint.sh

git:
  depth: 5
